config/routes.rb
EmberCartExample::Application.routes.draw do
  mount EmberCart::Engine => "ember_cart", as: :ember_cart

  root :to => 'product_categories#index'

  resources :product_categories do
    resources :products
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_ancestry
  acts_as_cartable

  belongs_to :product_category

  attr_accessible :group, :name, :price
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  has_many :products

  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :load_or_create_carts

  helper_method :ember_carts, :current_cart
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @product_category = ProductCategory.find(params[:product_category_id])
    @products = @product_category.products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype
html lang="en"
  head
    title= content_for?(:title) ? yield(:title) : "EmberCartExample"
    meta charset="utf-8"
    = csrf_meta_tags
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /![if lt IE 9]
      | <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="#{root_path}" EmberCartExample
          .container-fluid.nav-collapse
            ul.nav.pull-right
              li id="ember-cart"
                script type="text/x-handlebars" {{view EmberCart.MiniCartBar}}
          /! /.nav-collapse
    .container-fluid
      - flash.each do |name, msg|
        div class="alert alert-#{ name == :notice ? "success" : "error"}"
          a.close data-dismiss="alert"
          = msg
      .row-fluid
        .span3
          .well.sidebar-nav
            ul.nav.nav-list
              li.nav-header Product Categories
              - ProductCategory.all.each do |c|
                li class="#{@product_category.name == c.name ? 'active' : '' if @product_category}"= link_to c.name.capitalize, product_category_products_path(c)
          /! /.well
        /! /span
        .span9
          .hero-unit
            h1 Welcome to EmberCartExample
          = yield
      /! /row
      footer
        p &copy; 2011-2012 Beijing Menglifang Network Science and Technology Co.,Ltd.

app/views/products/index.html.slim
- (@products.count / 3 + 1).times do |i|
  div.row
    - @products[(i * 3)..((i + 1) * 3 - 1)].each do |p, i|
      div.span4
        p: h3= p.name
        p= "Price: #{number_to_currency(p.price)}"
        p: a.btn.btn-danger.btn-large.add-to-cart data-product="#{ ProductSerializer.new(p).as_json[:product].to_json.gsub(/"/, "\"") }" Add to cart
        - if p.has_children?
          p: h4 Composed of:
          ul
            - p.children.each do |c|
              li= "#{c.name} (#{number_to_currency(c.price)})"

coffee:
  jQuery ->
    jQuery('a.add-to-cart').click ->
      product = $(this).data().product

      cartItemAttrs =
        cartable_type: 'Product'
        cartable_id: product.id
        name: product.name
        price: product.price
        quantity: 1
        children: []

      cartItemAttrs.children.push(
        cartable_type: 'Product'
        cartable_id: c.id
        name: c.name
        price: c.price
        quantity: 1
        children: []
      ) for c in product.children

      EmberCart.cartsController.addCartItem cartItemAttrs